---
- name: install php
  pkgng:
    name: '{{ fpm_pkg_name }}'
    state: present
  notify: restart fpm

- name: php.ini
  copy:
    src: /usr/local/etc/php.ini-production
    dest: /usr/local/etc/php.ini
    force: no
    remote_src: yes

- name: php-cli.ini
  copy:
    src: /usr/local/etc/php.ini-development
    dest: /usr/local/etc/php-cli.ini
    force: no
    remote_src: yes

- name: enable php-fpm
  lineinfile:
    line: 'php_fpm_enable="YES"'
    state: present
    regexp: '^php_fpm_enable='
    dest: /etc/rc.conf

- name: umask php-fpm
  lineinfile:
    line: 'php_fpm_umask="{{ php_fpm_umask | default("022") }}"'
    state: present
    regexp: '^php_fpm_umask='
    dest: /etc/rc.conf
  when: php_fpm_umask | default(False)
  notify: restart fpm

