---
- name: install php
  pkgng:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ fpm_pkg_name }}'

- name: enable php-fpm
  lineinfile:
    line: 'php_fpm_enable="YES"'
    state: present
    regexp: '^php_fpm_enable='
    dest: /etc/rc.conf
