---
- name: install php
  pkgng:
    name: '{{ fpm_pkg_name }}'
    state: present
  notify: restart fpm

- name: enable php-fpm
  lineinfile:
    line: 'php_fpm_enable="YES"'
    state: present
    regexp: '^php_fpm_enable='
    dest: /etc/rc.conf
