---
- name: install php
  pkgng:
    name: '{{ fpm_pkg_name }}'
    state: present
  notify: restart fpm

- name: list php packages names
  shell: 'pkg search -L name php{{ php_version | regex_replace("\.","") }} | cut -d" " -f1'
  register: php_packages_available
  check_mode: False
  ignore_errors: True
  changed_when: False

- name: install php packages
  pkgng:
    state: present
    name: '{{ item }}'
  loop: '{{ php_packages_available.stdout_lines }}'
  when: item | regex_replace("^.*-","") in php_modules | default([])
  notify: restart fpm

- name: php.ini
  copy:
    src: /usr/local/etc/php.ini-production
    dest: /usr/local/etc/php.ini
    force: no
    remote_src: yes

- name: php-cli.ini
  copy:
    src: /usr/local/etc/php.ini-development
    dest: /usr/local/etc/php-cli.ini
    force: no
    remote_src: yes

- name: enable php-fpm
  lineinfile:
    line: 'php_fpm_enable="YES"'
    state: present
    regexp: '^php_fpm_enable='
    dest: /etc/rc.conf

- name: umask php-fpm
  lineinfile:
    line: 'php_fpm_umask="{{ php_fpm_umask | default("022") }}"'
    state: present
    regexp: '^php_fpm_umask='
    dest: /etc/rc.conf
  when: php_fpm_umask | default(False)
  notify: restart fpm

