---
- include: '{{ ansible_distribution }}.yml'
  tags: phpfpm, pkg

- include_vars: '{{ ansible_os_family }}.yml'
  tags: vars, phpfpm

- name: default config
  template: 
    src: php-fpm.conf.j2
    dest: '{{ fpm_conf }}'
  tags: phpfpm, config

# TODO - name: cron tmp

- debug: var=sites

- name: mkdir php-fpm.d
  file:
    path: '{{ fpm_pools_dir }}'
    state: directory
  tags: phpfpm, config

- name: php-fpm sites
  include: 'phpapp.yml'
  with_items: '{{ sites }}'
  loop_control:
    loop_var: phpsite
  tags: phpfpm, sites

- name: start php-fpm
  service:
    name: '{{ fpm_service }}'
    state: started
  tags: phpfpm
