---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_os_family }}.yml'
  tags: vars, phpfpm

- include_tasks: '{{ ansible_distribution }}.yml'
  tags: phpfpm, pkg

- block:
  - name: php-fpm.conf
    template:
      src: php-fpm.conf.j2
      dest: '{{ fpm_conf }}'
  - name: php.ini
    template:
      src: '{{ phpinifile }}'
      dest: '{{ phpinidest }}'
    with_first_found:
      - 'php.ini-{{ ansible-distribution }}.j2'
      - php.ini.j2
    loop_control:
      loop_var: phpinifile
  - name: php.ini cli
    template:
      src: '{{ phpinifile }}'
      dest: '{{ phpiniclidest }}'
    with_first_found:
      - 'php-cli.ini-{{ ansible-distribution }}.j2'
      - php-cli.ini.j2
      - php.ini.j2
    loop_control:
      loop_var: phpinifile
  tags: phpfpm, config

- name: mkdir php-fpm.d
  file:
    path: '{{ fpm_pools_dir }}'
    state: directory
  tags: phpfpm, config

- name: php-fpm sites
  include_tasks: 'phpapp.yml'
  with_items: '{{ sites }}'
  loop_control:
    loop_var: phpsite
  when: '"backend" in phpsite and phpsite.backend == "php-fpm"'
  tags: phpfpm, sites

- name: start php-fpm
  service:
    name: '{{ fpm_service }}'
    state: started
  tags: phpfpm
