---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
      - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      - '{{ ansible_os_family }}.yml'
  tags: vars, phpfpm

- include_tasks: '{{ ansible_distribution }}.yml'
  tags: phpfpm, pkg

- block:
  - name: php-fpm.conf
    template:
      src: php-fpm.conf.j2
      dest: '{{ fpm_conf }}'
  - name: php.ini
    lineinfile:
      dest: '{{ phpinidest }}'
      line: '{{ phpini.key }}={{ phpini.value }}'
      regexp: '^{{ phpini.key }}='
      insertafter: '{{ phpini.key }}'
    with_dict: '{{ php_ini_vars }}'
    when: php_ini_vars
    loop_control:
      loop_var: phpini
  - name: php-cli.ini
    lineinfile:
      dest: '{{ phpiniclidest }}'
      line: '{{ phpini.key }}={{ phpini.value }}'
      regexp: '^{{ phpini.key }}='
      insertafter: '{{ phpini.key }}'
    with_dict: '{{ php_ini_vars }}'
    when: php_ini_vars
    loop_control:
      loop_var: phpini
  - name: php-fpm.ini
    lineinfile:
      dest: '{{ phpinifpmdest }}'
      line: '{{ phpini.key }}={{ phpini.value }}'
      regexp: '^{{ phpini.key }}='
      insertafter: '{{ phpini.key }}'
    with_dict: '{{ php_ini_vars }}'
    when: php_ini_vars and phpinifpmdest
    loop_control:
      loop_var: phpini
  tags: phpfpm, config

- name: mkdir php-fpm.d
  file:
    path: '{{ fpm_pools_dir }}'
    state: directory
  tags: phpfpm, config

- name: php-fpm sites
  include_tasks: 'phpapp.yml'
  with_items: '{{ sites }}'
  loop_control:
    loop_var: phpsite
  when: '"backend" in phpsite and phpsite.backend == "php-fpm"'
  tags: phpfpm, sites

- name: start php-fpm
  service:
    name: '{{ fpm_service }}'
    state: started
  tags: phpfpm
