---
- name: restart fpm
  service:
    name: '{{ fpm_service }}'
    state: restarted

- name: reload fpm
  service:
    name: '{{ fpm_service }}'
    state: reloaded

- name: rebuild login.conf database
  command: /usr/bin/cap_mkdb /etc/login.conf
